# vim: set tabstop=8 softtabstop=8 noexpandtab:

node-cli:
	docker-compose run --service-ports --rm node-cli

node-update:
	docker-compose run --no-deps --rm node-cli npm install

node-dist:
	docker-compose run --no-deps --rm node-cli bash -c 'npm install && grunt dist'

node-check-code:
	docker-compose run --no-deps --rm node-cli grunt check-code

node-fix-code:
	docker-compose run --no-deps --rm node-cli grunt fix-code
