# vim: set tabstop=8 softtabstop=8 noexpandtab:

node-cli:
	docker-compose run --service-ports --rm node-cli

node-check:
	docker-compose run --no-deps --rm --entrypoint="bash -c 'npm run check'" node-cli

node-dist:
	docker-compose run --no-deps --rm --entrypoint="bash -c 'npm install && grunt dist'" node-cli
