# vim: set tabstop=8 softtabstop=8 noexpandtab:

node-cli:
	docker-compose run --service-ports --rm node-cli

node-update:
	docker-compose run --no-deps --rm --entrypoint="npm install" node-cli

node-dist:
	docker-compose run --no-deps --rm --entrypoint="bash -c 'npm install && grunt dist'" node-cli

node-check-code:
	docker-compose run --no-deps --rm --entrypoint="grunt check-code" node-cli

node-fix-code:
	docker-compose run --no-deps --rm --entrypoint="grunt fix-code" node-cli
